2025-05-01 20:27:30,681 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:27:38,451 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'Saab__Työsopimus.pdf'}}
2025-05-01 20:27:38,705 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:27:48,040 INFO {'route': 'MFA_SETUP', 'event': 'QR_CODE_GENERATED', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'QR code generated for MFA setup', 'extra_data': None}
2025-05-01 20:27:51,093 INFO {'route': 'LOGOUT', 'event': 'USER_LOGOUT', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'User logged out', 'extra_data': None}
2025-05-01 20:29:06,889 INFO {'route': 'REGISTER', 'event': 'SUCCESSFUL_REGISTRATION', 'user_id': UUID('a6733e32-34a2-4310-9af8-43fb5d1c5df4'), 'message': 'User registered successfully', 'extra_data': None}
2025-05-01 20:29:17,491 INFO {'route': 'LOGIN', 'event': 'FAILED_LOGIN', 'user_id': 'Tuukka', 'message': 'Invalid credentials', 'extra_data': {'reason': 'Incorrect username or password'}}
2025-05-01 20:29:24,184 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('a6733e32-34a2-4310-9af8-43fb5d1c5df4'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:29:49,010 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:29:49,273 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:29:59,261 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'Ryhmä_4_tietokanta (1).pdf'}}
2025-05-01 20:29:59,809 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:31:50,273 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:31:50,538 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:31:50,586 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:31:50,591 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:31:59,638 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:31:59,902 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:31:59,948 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:31:59,952 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:32:30,616 INFO {'route': 'MFA_SETUP', 'event': 'QR_CODE_GENERATED', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'QR code generated for MFA setup', 'extra_data': None}
2025-05-01 20:32:34,717 INFO {'route': 'MFA_SETUP_VERIFY', 'event': 'INVALID_TOTP_CODE', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Invalid TOTP code', 'extra_data': None}
2025-05-01 20:32:48,812 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:32:49,074 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:32:53,710 INFO {'route': 'FILE_DELETE', 'event': 'SUCCESSFUL_DELETE', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'File deleted successfully', 'extra_data': {'file_id': '863ab0fa-ddf9-4ba4-bfb3-036eb07eed62'}}
2025-05-01 20:32:53,968 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'a6733e32-34a2-4310-9af8-43fb5d1c5df4', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:44:56,992 INFO {'route': 'GITHUB_CALLBACK', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('e4c024de-f68b-421e-a9d2-04872bb8e61b'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:44:58,300 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:44:58,565 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:44:59,491 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:45:00,099 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:45:04,116 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'Ryhmä_4_tietokanta.pdf'}}
2025-05-01 20:45:04,438 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:45:08,310 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': '2025_IoT_DataPrivacy.docx'}}
2025-05-01 20:45:08,635 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:45:19,636 INFO {'route': 'FILE_DOWNLOAD', 'event': 'SUCCESSFUL_DOWNLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File downloaded successfully', 'extra_data': {'filename': '2025_IoT_DataPrivacy.docx'}}
2025-05-01 20:46:13,331 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:46:13,557 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:47:39,358 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:47:39,489 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:47:39,684 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:47:39,690 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:48:34,650 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'JagexLauncher.exe'}}
2025-05-01 20:48:34,706 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:48:43,332 INFO {'route': 'FILE_DOWNLOAD', 'event': 'SUCCESSFUL_DOWNLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File downloaded successfully', 'extra_data': {'filename': 'JagexLauncher.exe'}}
2025-05-01 20:52:59,404 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'vk_swiftshader_icd.json'}}
2025-05-01 20:52:59,672 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:53:08,722 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:53:09,030 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-01 20:53:09,341 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:53:09,683 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:53:15,744 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'vk_swiftshader_icd.json'}}
2025-05-01 20:53:16,094 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-01 20:57:26,935 INFO {'route': 'FILE_DELETE_ALL', 'event': 'SUCCESSFUL_DELETE_ALL', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'All files deleted successfully', 'extra_data': None}
2025-05-01 20:57:26,946 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:49:40,858 INFO {'route': 'REFRESH_TOKEN', 'event': 'VALID_REFRESH_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid refresh token', 'extra_data': {'mfa_enabled': False}}
2025-05-03 18:49:40,859 INFO {'route': 'REFRESH_TOKEN', 'event': 'VALID_REFRESH_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid refresh token', 'extra_data': {'mfa_enabled': False}}
2025-05-03 18:49:44,512 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:49:44,817 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:50:21,036 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'Kohteen_suostumus-1744813009445.pdf'}}
2025-05-03 18:50:21,362 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:50:25,633 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'Kohteen_suostumus-1744813009445.pdf'}}
2025-05-03 18:50:25,875 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:50:29,938 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'Saab__Työsopimus_allekirjoitettu.pdf'}}
2025-05-03 18:50:30,574 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:51:31,193 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 18:51:31,423 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 18:51:31,508 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:51:31,517 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:52:32,066 INFO {'route': 'FILE_DOWNLOAD_ALL', 'event': 'SUCCESSFUL_DOWNLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File downloaded successfully', 'extra_data': {'filename': 'Saab__Työsopimus_allekirjoitettu.pdf'}}
2025-05-03 18:53:21,817 INFO {'route': 'FILE_DOWNLOAD_ALL', 'event': 'SUCCESSFUL_DOWNLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File downloaded successfully', 'extra_data': {'filename': 'Saab__Työsopimus_allekirjoitettu.pdf'}}
2025-05-03 18:54:21,170 INFO {'route': 'FILE_DELETE', 'event': 'SUCCESSFUL_DELETE', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File deleted successfully', 'extra_data': {'file_id': '136d66f0-2c8a-4e89-8bcd-956d45cc5841'}}
2025-05-03 18:54:21,394 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:54:25,666 INFO {'route': 'FILE_DELETE', 'event': 'SUCCESSFUL_DELETE', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File deleted successfully', 'extra_data': {'file_id': '93716274-4a26-4631-a3c3-f2dc88f71523'}}
2025-05-03 18:54:25,987 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 18:54:28,524 INFO {'route': 'FILE_DELETE_ALL', 'event': 'SUCCESSFUL_DELETE_ALL', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'All files deleted successfully', 'extra_data': None}
2025-05-03 18:54:29,155 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 19:01:31,884 INFO {'route': 'REFRESH_TOKEN', 'event': 'VALID_REFRESH_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid refresh token', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:04:37,965 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'File uploaded successfully', 'extra_data': {'filename': '2025_IoT_DataPrivacy (1).docx'}}
2025-05-03 19:04:38,073 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 19:04:40,751 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "download_files() missing 1 required positional argument: 'file_id'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: download_files() missing 1 required positional argument: \'file_id\'\n'}}
2025-05-03 19:04:42,578 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "download_files() missing 1 required positional argument: 'file_id'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: download_files() missing 1 required positional argument: \'file_id\'\n'}}
2025-05-03 19:04:46,415 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "download_files() missing 1 required positional argument: 'file_id'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: download_files() missing 1 required positional argument: \'file_id\'\n'}}
2025-05-03 19:08:30,146 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "download_files() missing 1 required positional argument: 'file_id'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: download_files() missing 1 required positional argument: \'file_id\'\n'}}
2025-05-03 19:09:25,442 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "download_files() missing 1 required positional argument: 'file_id'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\nTypeError: download_files() missing 1 required positional argument: \'file_id\'\n'}}
2025-05-03 19:10:07,493 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:07,500 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 19:10:07,579 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:07,582 INFO {'route': 'FILE_DELETE', 'event': 'SUCCESSFUL_DELETE', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'File deleted successfully', 'extra_data': {'file_id': '5af93446-6d8f-4330-afe8-378cd936af1c'}}
2025-05-03 19:10:07,584 INFO {'route': 'FILE_DELETE', 'event': 'FILE_NOT_FOUND', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'File not found in database', 'extra_data': {'file_id': '5af93446-6d8f-4330-afe8-378cd936af1d'}}
2025-05-03 19:10:07,585 INFO {'route': 'FILE_DELETE', 'event': 'INVALID_FILE_ID', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'Invalid file ID', 'extra_data': None}
2025-05-03 19:10:07,662 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:07,666 INFO {'route': 'FILE_DOWNLOAD', 'event': 'SUCCESSFUL_DOWNLOAD', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'File downloaded successfully', 'extra_data': {'filename': 'test.txt'}}
2025-05-03 19:10:07,667 INFO {'route': 'FILE_DOWNLOAD', 'event': 'FILE_NOT_FOUND', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'File not found in database', 'extra_data': None}
2025-05-03 19:10:07,668 INFO {'route': 'FILE_DOWNLOAD', 'event': 'INVALID_FILE_ID', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'Invalid file ID', 'extra_data': None}
2025-05-03 19:10:07,745 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:07,770 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'test_file.txt'}}
2025-05-03 19:10:08,113 INFO {'route': 'FILE_UPLOAD', 'event': 'SUCCESSFUL_UPLOAD', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'File uploaded successfully', 'extra_data': {'filename': 'max_size_file.txt'}}
2025-05-03 19:10:12,380 INFO {'route': 'FILE_UPLOAD', 'event': 'FILE_SIZE_EXCEEDED', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'File size exceeds limit', 'extra_data': None}
2025-05-03 19:10:12,478 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:12,564 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:12,567 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:12,643 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:12,662 INFO {'route': 'REFRESH_TOKEN', 'event': 'VALID_REFRESH_TOKEN', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'Valid refresh token', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:12,665 INFO {'route': 'LOGIN', 'event': 'FAILED_LOGIN', 'user_id': 'NonExistentUser', 'message': 'Invalid credentials', 'extra_data': {'reason': 'Incorrect username or password'}}
2025-05-03 19:10:12,667 INFO {'route': 'LOGIN', 'event': 'INVALID_LOGIN_INPUT', 'user_id': 'Testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:12,668 INFO {'route': 'LOGIN', 'event': 'INVALID_LOGIN_INPUT', 'user_id': 'Testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:12,668 INFO {'route': 'LOGIN', 'event': 'INVALID_LOGIN_INPUT', 'user_id': 'Testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:12,743 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMiwianRpIjoiOGEwOWQyMDAtOGU2NC00M2JlLTg4MjMtNjc0ZjNmN2M4MWFjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMiwiY3NyZiI6IjliOTMyYzEwLTZhODAtNDE5Yy1iZTcxLWUwNzg4ZDMyZDFlZSIsImV4cCI6MTc0NjI4ODkxMiwidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.KUq37S7t10LN4IyzBg7g-sJvAjdgjD7XaPYl8FMu-9c'}}
2025-05-03 19:10:12,746 INFO {'route': 'LOGOUT', 'event': 'USER_LOGOUT', 'user_id': None, 'message': 'User logged out', 'extra_data': None}
2025-05-03 19:10:12,824 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMiwianRpIjoiM2RjNDJmNTYtMTdlZS00NDU5LTkyY2EtMDNiODUyYzY1YzQwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMiwiY3NyZiI6ImM2MWE2NWRmLTk0YjEtNGE3MS1hNjRhLWI1NmExNGE2ZjJjYiIsImV4cCI6MTc0NjI4ODkxMiwidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.-pP9LHsCf_h6uD5DKwLSsNw30vdgPPs7dHGxwacUjq4'}}
2025-05-03 19:10:12,835 INFO {'route': 'VERIFY_MFA', 'event': 'SUCCESSFUL_VERIFICATION', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'MFA verification successful', 'extra_data': None}
2025-05-03 19:10:12,910 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMiwianRpIjoiNDA4NjQ0ZTktNjA0Mi00MTk1LWI4ZjItZDE2NzA5M2EyNDg5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMiwiY3NyZiI6ImRkMTAxNzg2LTEwZDEtNDc3MC04ZTAxLWU3YjQ1NDEzZmU1ZiIsImV4cCI6MTc0NjI4ODkxMiwidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.BEIrRgCtgMe6cwxAlGUX4tKxOdxm-TgbXEp8vsnJQLk'}}
2025-05-03 19:10:12,913 INFO {'route': 'VERIFY_MFA', 'event': 'INVALID_TOTP_CODE', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'Invalid TOTP code', 'extra_data': None}
2025-05-03 19:10:12,990 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMiwianRpIjoiNjdiZmU1NjQtNWQ2My00ZWY4LTlkYzMtMWUyNmZhYTU1Mjg1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMiwiY3NyZiI6IjAxMTAxOTJmLTVlNzItNGM4NC05MDMwLWE0ZTNlY2NhYmY1OCIsImV4cCI6MTc0NjI4ODkxMiwidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.wQE5rwm6IvRfhxcsDYmQqWSVzEXmYi5ICVjnShHgZ18'}}
2025-05-03 19:10:12,992 INFO {'route': 'VERIFY_MFA', 'event': 'INVALID_TOTP_CODE', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'Invalid TOTP code', 'extra_data': None}
2025-05-03 19:10:13,067 INFO {'route': 'LOGIN', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('fc9d3443-0c93-4142-9b64-cd79d123fe17'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:10:13,124 INFO {'route': 'MFA_SETUP', 'event': 'QR_CODE_GENERATED', 'user_id': 'fc9d3443-0c93-4142-9b64-cd79d123fe17', 'message': 'QR code generated for MFA setup', 'extra_data': None}
2025-05-03 19:10:13,198 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMywianRpIjoiNWM2NmVmNjEtZTc2Mi00MWM1LWI0NmUtMjdiNDk4ZWY3YzFjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMywiY3NyZiI6ImM4MzNmM2Y4LTkwN2ItNDZlYS1iNjZlLWQ3NTkzMGNkMGNkNiIsImV4cCI6MTc0NjI4ODkxMywidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.2qYYwC-w2jd1aHStqmpvp4iPfgRWWeKpMX_-xtYmkxI'}}
2025-05-03 19:10:13,201 INFO {'route': 'MFA_SETUP', 'event': 'MFA_ALREADY_ENABLED', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'MFA already enabled for user', 'extra_data': None}
2025-05-03 19:10:13,275 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMywianRpIjoiNWQ1N2E1NzYtZjIxMy00NjIzLWJjYWYtZmYxODc1ZjFiZTlhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMywiY3NyZiI6IjM1NGIyMzNjLWRlOWMtNDBkYS05ZDI5LTBhODIyMmY1YzIyZSIsImV4cCI6MTc0NjI4ODkxMywidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.dXDbxcyp91UkbZzS-SOxxU_f3efmPNQHtbWLKlhUpHs'}}
2025-05-03 19:10:13,279 INFO {'route': 'MFA_DISABLE', 'event': 'SUCCESSFUL_VERIFICATION', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'MFA removal verification successful', 'extra_data': None}
2025-05-03 19:10:13,354 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMywianRpIjoiOTJjZGVmOTYtY2RjZi00ZDRkLThiOTQtZWE2NWNkOGFlNDc1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMywiY3NyZiI6IjgwZDUxOTU1LTY2MWItNDhhYy1iZTJhLTBlNjY0M2IzNGRiNCIsImV4cCI6MTc0NjI4ODkxMywidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.76vJWKDGkN5uvi9235NSvKxTGUwXcj8PcpfnLpwOT9k'}}
2025-05-03 19:10:13,357 INFO {'route': 'MFA_DISABLE', 'event': 'INVALID_TOTP_CODE', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'Invalid TOTP code', 'extra_data': None}
2025-05-03 19:10:13,431 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMywianRpIjoiMDg2NGQ4MzMtYzg2NS00NmI2LTk2OWQtYWZkMWE0OTBlOGRhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMywiY3NyZiI6ImU0NGY0ZDQ4LTFhMjMtNDY3MS05MTU4LTg5OGJmNGMxMTNmOCIsImV4cCI6MTc0NjI4ODkxMywidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.DBMexxGIrVlUHiaO2Co6-OEs4wlTXXafqgfTCCq8lEk'}}
2025-05-03 19:10:13,434 INFO {'route': 'MFA_SETUP_VERIFY', 'event': 'SUCCESSFUL_VERIFICATION', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'MFA setup verification successful', 'extra_data': None}
2025-05-03 19:10:13,513 INFO {'route': 'LOGIN', 'event': 'MFA_REQUIRED', 'user_id': UUID('d7a3fc1b-6a82-49a3-b896-9390f985482e'), 'message': 'MFA token required', 'extra_data': {'temporary_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0NjI4ODYxMywianRpIjoiOTU0OTU1ODktNDc5Zi00YTlmLTg0ZjktN2E5YjRjYWI2MTI5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImQ3YTNmYzFiLTZhODItNDlhMy1iODk2LTkzOTBmOTg1NDgyZSIsIm5iZiI6MTc0NjI4ODYxMywiY3NyZiI6IjMwNDdkZjU5LTI2Y2MtNDg3YS04NDJhLTE0YjE4YWMxODQ0NiIsImV4cCI6MTc0NjI4ODkxMywidGVtcG9yYXJ5X3Rva2VuIjp0cnVlfQ.IVf1Jy2WSCDHeB1i7AxotzO8pJ4a0WSfKp9o7qGo8co'}}
2025-05-03 19:10:13,516 INFO {'route': 'MFA_SETUP_VERIFY', 'event': 'INVALID_TOTP_CODE', 'user_id': 'd7a3fc1b-6a82-49a3-b896-9390f985482e', 'message': 'Invalid TOTP code', 'extra_data': None}
2025-05-03 19:10:13,523 INFO {'route': 'GOOGLE_CALLBACK', 'event': 'SUCCESSFUL_LOGIN', 'user_id': None, 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': None}}
2025-05-03 19:10:13,524 INFO {'route': 'GOOGLE_CALLBACK', 'event': 'INVALID_TOKEN', 'user_id': None, 'message': 'Invalid token', 'extra_data': {'token': None}}
2025-05-03 19:10:13,528 INFO {'route': 'GITHUB_CALLBACK', 'event': 'SUCCESSFUL_LOGIN', 'user_id': None, 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': None}}
2025-05-03 19:10:13,529 INFO {'route': 'GITHUB_CALLBACK', 'event': 'INVALID_TOKEN', 'user_id': None, 'message': 'Invalid token', 'extra_data': {'token': None}}
2025-05-03 19:10:13,605 INFO {'route': 'REGISTER', 'event': 'SUCCESSFUL_REGISTRATION', 'user_id': None, 'message': 'User registered successfully', 'extra_data': None}
2025-05-03 19:10:13,608 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 'testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:13,608 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 'testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:13,609 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 'testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:13,609 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 'testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:13,610 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 'testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:13,610 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 'testuser', 'message': 'Invalid password format (8-64 chars, at least one uppercase, lowercase, and digit, no spaces)', 'extra_data': None}
2025-05-03 19:10:13,612 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 't', 'message': 'Invalid username/email format', 'extra_data': None}
2025-05-03 19:10:13,612 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': 'user@@', 'message': 'Invalid username/email format', 'extra_data': None}
2025-05-03 19:10:13,613 INFO {'route': 'REGISTER', 'event': 'INVALID_REGISTER_INPUT', 'user_id': '123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789', 'message': 'Invalid username/email format', 'extra_data': None}
2025-05-03 19:11:31,857 INFO {'route': 'REFRESH_TOKEN', 'event': 'VALID_REFRESH_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid refresh token', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:21:31,842 INFO {'route': 'REFRESH_TOKEN', 'event': 'VALID_REFRESH_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid refresh token', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:31:31,835 INFO {'route': 'REFRESH_TOKEN', 'event': 'VALID_REFRESH_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid refresh token', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:39:43,846 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User(users)]'. Original exception was: Error creating backref 'user' on relationship 'User.files': property of that name exists on mapper 'Mapper[UploadedFile(uploaded_files)]'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\app\\routes.py", line 34, in check_token\n    user = User.query.filter_by(id=current_user).first()\n           ^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_sqlalchemy\\model.py", line 22, in __get__\n    return cls.query_class(\n           ~~~~~~~~~~~~~~~^\n        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 276, in __init__\n    self._set_entities(entities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 289, in _set_entities\n    coercions.expect(\n    ~~~~~~~~~~~~~~~~^\n        roles.ColumnsClauseRole,\n        ^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n        post_inspect=True,\n        ^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py", line 388, in expect\n    insp._post_inspect\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 1257, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n                                           ~~~~~~~~~^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2724, in _post_inspect\n    self._check_configure()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2401, in _check_configure\n    _configure_registries({self.registry}, cascade=True)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4214, in _configure_registries\n    _do_configure_registries(registries, cascade)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4251, in _do_configure_registries\n    raise e\nsqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can\'t proceed with initialization of other mappers. Triggering mapper: \'Mapper[User(users)]\'. Original exception was: Error creating backref \'user\' on relationship \'User.files\': property of that name exists on mapper \'Mapper[UploadedFile(uploaded_files)]\'\n'}}
2025-05-03 19:39:43,850 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "Error creating backref 'user' on relationship 'User.files': property of that name exists on mapper 'Mapper[UploadedFile(uploaded_files)]'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\app\\routes.py", line 34, in check_token\n    user = User.query.filter_by(id=current_user).first()\n           ^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_sqlalchemy\\model.py", line 22, in __get__\n    return cls.query_class(\n           ~~~~~~~~~~~~~~~^\n        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 276, in __init__\n    self._set_entities(entities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 289, in _set_entities\n    coercions.expect(\n    ~~~~~~~~~~~~~~~~^\n        roles.ColumnsClauseRole,\n        ^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n        post_inspect=True,\n        ^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py", line 388, in expect\n    insp._post_inspect\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 1257, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n                                           ~~~~~~~~~^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2724, in _post_inspect\n    self._check_configure()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2401, in _check_configure\n    _configure_registries({self.registry}, cascade=True)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4214, in _configure_registries\n    _do_configure_registries(registries, cascade)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4255, in _do_configure_registries\n    mapper._post_configure_properties()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2418, in _post_configure_properties\n    prop.init()\n    ~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\interfaces.py", line 589, in init\n    self.do_init()\n    ~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\relationships.py", line 1661, in do_init\n    self._generate_backref()\n    ~~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\relationships.py", line 2089, in _generate_backref\n    raise sa_exc.ArgumentError(\n    ...<4 lines>...\n    )\nsqlalchemy.exc.ArgumentError: Error creating backref \'user\' on relationship \'User.files\': property of that name exists on mapper \'Mapper[UploadedFile(uploaded_files)]\'\n'}}
2025-05-03 19:39:44,096 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User(users)]'. Original exception was: Error creating backref 'user' on relationship 'User.files': property of that name exists on mapper 'Mapper[UploadedFile(uploaded_files)]'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\app\\routes.py", line 55, in refresh\n    user = User.query.filter_by(id=current_user).first()\n           ^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_sqlalchemy\\model.py", line 22, in __get__\n    return cls.query_class(\n           ~~~~~~~~~~~~~~~^\n        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 276, in __init__\n    self._set_entities(entities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 289, in _set_entities\n    coercions.expect(\n    ~~~~~~~~~~~~~~~~^\n        roles.ColumnsClauseRole,\n        ^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n        post_inspect=True,\n        ^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py", line 388, in expect\n    insp._post_inspect\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 1257, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n                                           ~~~~~~~~~^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2724, in _post_inspect\n    self._check_configure()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2401, in _check_configure\n    _configure_registries({self.registry}, cascade=True)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4214, in _configure_registries\n    _do_configure_registries(registries, cascade)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4251, in _do_configure_registries\n    raise e\nsqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can\'t proceed with initialization of other mappers. Triggering mapper: \'Mapper[User(users)]\'. Original exception was: Error creating backref \'user\' on relationship \'User.files\': property of that name exists on mapper \'Mapper[UploadedFile(uploaded_files)]\'\n'}}
2025-05-03 19:39:44,167 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': "One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper[User(users)]'. Original exception was: Error creating backref 'user' on relationship 'User.files': property of that name exists on mapper 'Mapper[UploadedFile(uploaded_files)]'", 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\app\\routes.py", line 55, in refresh\n    user = User.query.filter_by(id=current_user).first()\n           ^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_sqlalchemy\\model.py", line 22, in __get__\n    return cls.query_class(\n           ~~~~~~~~~~~~~~~^\n        cls, session=cls.__fsa__.session()  # type: ignore[arg-type]\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 276, in __init__\n    self._set_entities(entities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\query.py", line 289, in _set_entities\n    coercions.expect(\n    ~~~~~~~~~~~~~~~~^\n        roles.ColumnsClauseRole,\n        ^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n        post_inspect=True,\n        ^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\coercions.py", line 388, in expect\n    insp._post_inspect\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 1257, in __get__\n    obj.__dict__[self.__name__] = result = self.fget(obj)\n                                           ~~~~~~~~~^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2724, in _post_inspect\n    self._check_configure()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 2401, in _check_configure\n    _configure_registries({self.registry}, cascade=True)\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4214, in _configure_registries\n    _do_configure_registries(registries, cascade)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\mapper.py", line 4251, in _do_configure_registries\n    raise e\nsqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can\'t proceed with initialization of other mappers. Triggering mapper: \'Mapper[User(users)]\'. Original exception was: Error creating backref \'user\' on relationship \'User.files\': property of that name exists on mapper \'Mapper[UploadedFile(uploaded_files)]\'\n'}}
2025-05-03 19:44:57,073 INFO {'route': 'GITHUB_CALLBACK', 'event': 'SUCCESSFUL_LOGIN', 'user_id': UUID('e4c024de-f68b-421e-a9d2-04872bb8e61b'), 'message': 'User successfully logged in', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:44:57,960 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:44:58,225 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:45:05,278 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 19:45:05,597 INFO {'route': 'FILE_LIST', 'event': 'SUCCESSFUL_LIST', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Files listed successfully', 'extra_data': None}
2025-05-03 19:45:17,768 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': '(psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n[SQL: UPDATE uploaded_files SET user_id=%(user_id)s::UUID WHERE uploaded_files.id = %(uploaded_files_id)s::UUID]\n[parameters: {\'user_id\': None, \'uploaded_files_id\': UUID(\'6d4497a9-a110-4924-9656-ecc51b9f987e\')}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1964, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py", line 945, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\npsycopg2.errors.NotNullViolation: null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\app\\routes.py", line 651, in delete_user\n    db.session.commit()\n    ~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\scoping.py", line 599, in commit\n    return self._proxied.commit()\n           ~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2032, in commit\n    trans.commit(_to_root=True)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File "<string>", line 2, in commit\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1313, in commit\n    self._prepare_impl()\n    ~~~~~~~~~~~~~~~~~~^^\n  File "<string>", line 2, in _prepare_impl\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1288, in _prepare_impl\n    self.session.flush()\n    ~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4353, in flush\n    self._flush(objects)\n    ~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4488, in _flush\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4449, in _flush\n    flush_context.execute()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 466, in execute\n    rec.execute(self)\n    ~~~~~~~~~~~^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 642, in execute\n    util.preloaded.orm_persistence.save_obj(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self.mapper,\n        ^^^^^^^^^^^^\n        uow.states_for_mapper_hierarchy(self.mapper, False, False),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        uow,\n        ^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 85, in save_obj\n    _emit_update_statements(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        base_mapper,\n        ^^^^^^^^^^^^\n    ...<3 lines>...\n        update,\n        ^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 912, in _emit_update_statements\n    c = connection.execute(\n        statement, multiparams, execution_options=execution_options\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1416, in execute\n    return meth(\n        self,\n        distilled_parameters,\n        execution_options or NO_OPTIONS,\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 523, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self, distilled_params, execution_options\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1638, in _execute_clauseelement\n    ret = self._execute_context(\n        dialect,\n    ...<8 lines>...\n        cache_hit=cache_hit,\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1843, in _execute_context\n    return self._exec_single_context(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^\n        dialect, context, statement, parameters\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1983, in _exec_single_context\n    self._handle_dbapi_exception(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        e, str_statement, effective_parameters, cursor, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 2352, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1964, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py", line 945, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\nsqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n[SQL: UPDATE uploaded_files SET user_id=%(user_id)s::UUID WHERE uploaded_files.id = %(uploaded_files_id)s::UUID]\n[parameters: {\'user_id\': None, \'uploaded_files_id\': UUID(\'6d4497a9-a110-4924-9656-ecc51b9f987e\')}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n'}}
2025-05-03 19:45:56,046 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': '(psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n[SQL: UPDATE uploaded_files SET user_id=%(user_id)s::UUID WHERE uploaded_files.id = %(uploaded_files_id)s::UUID]\n[parameters: {\'user_id\': None, \'uploaded_files_id\': UUID(\'6d4497a9-a110-4924-9656-ecc51b9f987e\')}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1964, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py", line 945, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\npsycopg2.errors.NotNullViolation: null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\app\\routes.py", line 651, in delete_user\n    db.session.commit()\n    ~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\scoping.py", line 599, in commit\n    return self._proxied.commit()\n           ~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2032, in commit\n    trans.commit(_to_root=True)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File "<string>", line 2, in commit\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1313, in commit\n    self._prepare_impl()\n    ~~~~~~~~~~~~~~~~~~^^\n  File "<string>", line 2, in _prepare_impl\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1288, in _prepare_impl\n    self.session.flush()\n    ~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4353, in flush\n    self._flush(objects)\n    ~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4488, in _flush\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4449, in _flush\n    flush_context.execute()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 466, in execute\n    rec.execute(self)\n    ~~~~~~~~~~~^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 642, in execute\n    util.preloaded.orm_persistence.save_obj(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self.mapper,\n        ^^^^^^^^^^^^\n        uow.states_for_mapper_hierarchy(self.mapper, False, False),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        uow,\n        ^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 85, in save_obj\n    _emit_update_statements(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        base_mapper,\n        ^^^^^^^^^^^^\n    ...<3 lines>...\n        update,\n        ^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 912, in _emit_update_statements\n    c = connection.execute(\n        statement, multiparams, execution_options=execution_options\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1416, in execute\n    return meth(\n        self,\n        distilled_parameters,\n        execution_options or NO_OPTIONS,\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 523, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self, distilled_params, execution_options\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1638, in _execute_clauseelement\n    ret = self._execute_context(\n        dialect,\n    ...<8 lines>...\n        cache_hit=cache_hit,\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1843, in _execute_context\n    return self._exec_single_context(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^\n        dialect, context, statement, parameters\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1983, in _exec_single_context\n    self._handle_dbapi_exception(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        e, str_statement, effective_parameters, cursor, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 2352, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1964, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py", line 945, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\nsqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n[SQL: UPDATE uploaded_files SET user_id=%(user_id)s::UUID WHERE uploaded_files.id = %(uploaded_files_id)s::UUID]\n[parameters: {\'user_id\': None, \'uploaded_files_id\': UUID(\'6d4497a9-a110-4924-9656-ecc51b9f987e\')}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n'}}
2025-05-03 19:46:48,929 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:46:48,929 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:46:51,654 INFO {'route': 'GLOBAL', 'event': 'EXCEPTION', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'An exception occurred', 'extra_data': {'error': '(psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n[SQL: UPDATE uploaded_files SET user_id=%(user_id)s::UUID WHERE uploaded_files.id = %(uploaded_files_id)s::UUID]\n[parameters: {\'user_id\': None, \'uploaded_files_id\': UUID(\'6d4497a9-a110-4924-9656-ecc51b9f987e\')}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'traceback': 'Traceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1964, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py", line 945, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\npsycopg2.errors.NotNullViolation: null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 917, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask\\app.py", line 902, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_limiter\\extension.py", line 1314, in __inner\n    return cast(R, flask.current_app.ensure_sync(obj)(*a, **k))\n                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\flask_jwt_extended\\view_decorators.py", line 170, in decorator\n    return current_app.ensure_sync(fn)(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\app\\routes.py", line 651, in delete_user\n    db.session.commit()\n    ~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\scoping.py", line 599, in commit\n    return self._proxied.commit()\n           ~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 2032, in commit\n    trans.commit(_to_root=True)\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^\n  File "<string>", line 2, in commit\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1313, in commit\n    self._prepare_impl()\n    ~~~~~~~~~~~~~~~~~~^^\n  File "<string>", line 2, in _prepare_impl\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\state_changes.py", line 139, in _go\n    ret_value = fn(self, *arg, **kw)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 1288, in _prepare_impl\n    self.session.flush()\n    ~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4353, in flush\n    self._flush(objects)\n    ~~~~~~~~~~~^^^^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4488, in _flush\n    with util.safe_reraise():\n         ~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py", line 146, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\session.py", line 4449, in _flush\n    flush_context.execute()\n    ~~~~~~~~~~~~~~~~~~~~~^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 466, in execute\n    rec.execute(self)\n    ~~~~~~~~~~~^^^^^^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py", line 642, in execute\n    util.preloaded.orm_persistence.save_obj(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self.mapper,\n        ^^^^^^^^^^^^\n        uow.states_for_mapper_hierarchy(self.mapper, False, False),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        uow,\n        ^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 85, in save_obj\n    _emit_update_statements(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        base_mapper,\n        ^^^^^^^^^^^^\n    ...<3 lines>...\n        update,\n        ^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\orm\\persistence.py", line 912, in _emit_update_statements\n    c = connection.execute(\n        statement, multiparams, execution_options=execution_options\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1416, in execute\n    return meth(\n        self,\n        distilled_parameters,\n        execution_options or NO_OPTIONS,\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py", line 523, in _execute_on_connection\n    return connection._execute_clauseelement(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        self, distilled_params, execution_options\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1638, in _execute_clauseelement\n    ret = self._execute_context(\n        dialect,\n    ...<8 lines>...\n        cache_hit=cache_hit,\n    )\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1843, in _execute_context\n    return self._exec_single_context(\n           ~~~~~~~~~~~~~~~~~~~~~~~~~^\n        dialect, context, statement, parameters\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1983, in _exec_single_context\n    self._handle_dbapi_exception(\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        e, str_statement, effective_parameters, cursor, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 2352, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\base.py", line 1964, in _exec_single_context\n    self.dialect.do_execute(\n    ~~~~~~~~~~~~~~~~~~~~~~~^\n        cursor, str_statement, effective_parameters, context\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File "D:\\OneDrive - TUNI.fi\\Secure Programming\\secure-auth\\backend\\venv\\Lib\\site-packages\\sqlalchemy\\engine\\default.py", line 945, in do_execute\n    cursor.execute(statement, parameters)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\nsqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "user_id" of relation "uploaded_files" violates not-null constraint\nDETAIL:  Failing row contains (6d4497a9-a110-4924-9656-ecc51b9f987e, null, 2025_IoT_DataPrivacy (1).docx, application/vnd.openxmlformats-officedocument.wordprocessingml.d..., 25533, \\xfa57aeb1f71d2b6522249e6a7012603a8550f24555d64e48496f8a724497ad..., \\x203cf9bbe692284e1132e11b657472442d15bb562d3eb4859bd46a79bb3e6f..., \\xf2cc1c755cf56987016cb96041a2b53e, \\xdd109175ee396826252c699343422c21, 2025-05-03 19:04:37.957958).\n\n[SQL: UPDATE uploaded_files SET user_id=%(user_id)s::UUID WHERE uploaded_files.id = %(uploaded_files_id)s::UUID]\n[parameters: {\'user_id\': None, \'uploaded_files_id\': UUID(\'6d4497a9-a110-4924-9656-ecc51b9f987e\')}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)\n'}}
2025-05-03 19:52:35,036 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
2025-05-03 19:52:35,036 INFO {'route': 'CHECK_TOKEN', 'event': 'VALID_TOKEN', 'user_id': 'e4c024de-f68b-421e-a9d2-04872bb8e61b', 'message': 'Valid token check', 'extra_data': {'mfa_enabled': False}}
